version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4070:8000"
    depends_on:
      - redis
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4069:5001"
    depends_on:
      - backend
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
